-- HU36: listas de precios con vigencia temporal y ajustes porcentuales.

create table if not exists public.lista_precio (
  id_lista_precio bigint generated by default as identity primary key,
  nombre text not null,
  fecha_desde date not null,
  fecha_hasta date,
  estado text not null default 'Borrador'
    check (estado in ('Borrador', 'Activa', 'Inactiva')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint lista_precio_nombre_check
    check (length(trim(nombre)) > 0),
  constraint lista_precio_fechas_check
    check (fecha_hasta is null or fecha_hasta >= fecha_desde),
  constraint lista_precio_nombre_fecha_unique
    unique (nombre, fecha_desde)
);

create table if not exists public.detalle_lista_precio (
  id_detalle_lista bigint generated by default as identity primary key,
  id_lista_precio bigint not null
    references public.lista_precio(id_lista_precio) on delete restrict,
  id_articulo integer not null
    references public.articulo(id_articulo) on delete restrict,
  precio_base numeric(14, 2) not null check (precio_base > 0),
  tipo_ajuste text not null default 'Sin ajuste'
    check (tipo_ajuste in ('Sin ajuste', 'Descuento', 'Recargo')),
  valor_ajuste numeric(7, 2) not null default 0 check (valor_ajuste >= 0),
  precio_final numeric(14, 2) generated always as (
    round(
      case
        when tipo_ajuste = 'Descuento' then precio_base * (1 - valor_ajuste / 100)
        when tipo_ajuste = 'Recargo' then precio_base * (1 + valor_ajuste / 100)
        else precio_base
      end,
      2
    )
  ) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint detalle_lista_articulo_unique
    unique (id_lista_precio, id_articulo),
  constraint detalle_lista_sin_ajuste_check
    check (tipo_ajuste <> 'Sin ajuste' or valor_ajuste = 0),
  constraint detalle_lista_descuento_check
    check (tipo_ajuste <> 'Descuento' or valor_ajuste < 100),
  constraint detalle_lista_precio_final_check
    check (precio_final > 0)
);

create index if not exists lista_precio_vigencia_idx
  on public.lista_precio (estado, fecha_desde, fecha_hasta);

create index if not exists detalle_lista_precio_articulo_idx
  on public.detalle_lista_precio (id_articulo);

-- Evita que dos listas generales activas sean aplicables a una misma fecha.
create or replace function public.validar_vigencia_lista_precio()
returns trigger
language plpgsql
as $$
begin
  if new.estado = 'Activa' and exists (
    select 1
    from public.lista_precio lp
    where lp.estado = 'Activa'
      and lp.id_lista_precio <> coalesce(new.id_lista_precio, 0)
      and daterange(lp.fecha_desde, lp.fecha_hasta, '[]')
          && daterange(new.fecha_desde, new.fecha_hasta, '[]')
  ) then
    raise exception 'Ya existe una lista de precios activa para parte de la vigencia indicada';
  end if;

  return new;
end;
$$;

drop trigger if exists lista_precio_vigencia_unica on public.lista_precio;
create trigger lista_precio_vigencia_unica
before insert or update of fecha_desde, fecha_hasta, estado
on public.lista_precio
for each row execute function public.validar_vigencia_lista_precio();

-- Mantiene updated_at sin depender del cliente.
create or replace function public.actualizar_lista_precio_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists lista_precio_actualizar_fecha on public.lista_precio;
create trigger lista_precio_actualizar_fecha
before update on public.lista_precio
for each row execute function public.actualizar_lista_precio_updated_at();

drop trigger if exists detalle_lista_precio_actualizar_fecha on public.detalle_lista_precio;
create trigger detalle_lista_precio_actualizar_fecha
before update on public.detalle_lista_precio
for each row execute function public.actualizar_lista_precio_updated_at();

-- Lista inicial para poder desarrollar y probar HU36 con los precios actuales.
insert into public.lista_precio (nombre, fecha_desde, fecha_hasta, estado)
values ('Lista general inicial', date '2026-09-17', null, 'Activa')
on conflict (nombre, fecha_desde) do nothing;

insert into public.detalle_lista_precio (
  id_lista_precio,
  id_articulo,
  precio_base,
  tipo_ajuste,
  valor_ajuste
)
select
  lp.id_lista_precio,
  a.id_articulo,
  a.precio_venta,
  'Sin ajuste',
  0
from public.lista_precio lp
cross join public.articulo a
where lp.nombre = 'Lista general inicial'
  and lp.fecha_desde = date '2026-09-17'
  and a.estado = true
  and a.precio_venta > 0
on conflict (id_lista_precio, id_articulo) do nothing;

-- Devuelve el precio aplicable o ninguna fila cuando el articulo no tiene precio vigente.
create or replace function public.obtener_precio_vigente(
  p_id_articulo integer,
  p_fecha_venta date default current_date
)
returns table (
  id_lista_precio bigint,
  nombre_lista text,
  precio_base numeric,
  tipo_ajuste text,
  valor_ajuste numeric,
  precio_final numeric
)
language sql
stable
as $$
  select
    lp.id_lista_precio,
    lp.nombre,
    dlp.precio_base,
    dlp.tipo_ajuste,
    dlp.valor_ajuste,
    dlp.precio_final
  from public.lista_precio lp
  join public.detalle_lista_precio dlp
    on dlp.id_lista_precio = lp.id_lista_precio
  where dlp.id_articulo = p_id_articulo
    and lp.estado = 'Activa'
    and lp.fecha_desde <= p_fecha_venta
    and (lp.fecha_hasta is null or lp.fecha_hasta >= p_fecha_venta)
  order by lp.fecha_desde desc
  limit 1;
$$;
