-- HU37/HU38: unicidad de clientes y registro del cobro de una venta.

begin;

create unique index if not exists cliente_dni_unique
  on public.cliente (dni)
  where dni is not null and trim(dni) <> '';

create unique index if not exists cliente_cuit_unique
  on public.cliente (cuit)
  where cuit is not null and trim(cuit) <> '';

create table if not exists public.pago_venta (
  id_pago_venta bigint generated by default as identity primary key,
  id_venta integer not null references public.venta(id_venta),
  id_medio_pago integer not null references public.medio_pago(id_medio_pago),
  importe numeric(14, 2) not null,
  referencia text,
  fecha_pago timestamptz not null default now(),
  constraint pago_venta_venta_unique unique (id_venta),
  constraint pago_venta_importe_positivo_check check (importe > 0)
);

create index if not exists pago_venta_medio_pago_idx
  on public.pago_venta (id_medio_pago);

grant select, insert on table public.pago_venta to anon, authenticated;
grant usage, select on sequence public.pago_venta_id_pago_venta_seq to anon, authenticated;

comment on table public.pago_venta is
  'Cobro asociado a una venta. En el Sprint 3 existe un único medio de pago por venta.';

commit;
