create table if not exists public.factura_proveedor (
  id_factura_proveedor bigint generated by default as identity primary key,
  id_proveedor bigint not null references public.proveedor(id_proveedor),
  id_orden_compra bigint null references public.orden_compra(id_orden_compra),
  tipo_comprobante text not null check (tipo_comprobante in ('Factura A', 'Factura B', 'Factura C')),
  punto_venta integer not null check (punto_venta between 1 and 99999),
  numero_comprobante text not null check (length(trim(numero_comprobante)) > 0),
  fecha date not null,
  subtotal numeric(14, 2) not null check (subtotal >= 0),
  iva numeric(14, 2) not null check (iva >= 0),
  conceptos_exentos numeric(14, 2) not null default 0 check (conceptos_exentos >= 0),
  conceptos_no_gravados numeric(14, 2) not null default 0 check (conceptos_no_gravados >= 0),
  importe_total numeric(14, 2) not null check (importe_total >= 0),
  estado text not null default 'Pendiente' check (estado in ('Pendiente', 'Pagada Parcial', 'Pagada', 'Anulada')),
  fecha_registro timestamptz not null default now(),
  constraint factura_proveedor_importe_total_check check (
    abs(importe_total - (subtotal + iva + conceptos_exentos + conceptos_no_gravados)) <= 0.01
  ),
  constraint factura_proveedor_numero_check check (numero_comprobante ~ '^[0-9]{1,8}$'),
  constraint factura_proveedor_comprobante_unique unique (id_proveedor, tipo_comprobante, punto_venta, numero_comprobante)
);

create index if not exists factura_proveedor_id_proveedor_idx on public.factura_proveedor(id_proveedor);
create index if not exists factura_proveedor_id_orden_compra_idx on public.factura_proveedor(id_orden_compra);