-- HU35: inicio, suspensión, recuperación y cancelación de ventas en borrador.
-- Los borradores se almacenan separados de las ventas emitidas para que no
-- consuman numeración fiscal ni requieran comprobantes temporales (TMP).

begin;

create table if not exists public.venta_borrador (
  id_borrador bigint generated by default as identity primary key,
  id_sucursal integer not null references public.sucursal(id_sucursal),
  id_deposito integer not null references public.deposito(id_deposito),
  id_cliente integer references public.cliente(id_cliente),
  id_lista integer references public.lista_precio(id_lista),
  id_medio_pago integer references public.medio_pago(id_medio_pago),
  referencia_pago text,
  importe_pagado numeric(14, 2),
  percepcion_iva numeric(14, 2) not null default 0,
  percepcion_iibb numeric(14, 2) not null default 0,
  idempotency_key uuid not null default gen_random_uuid(),
  estado text not null default 'Borrador',
  fecha_creacion timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now(),
  constraint venta_borrador_estado_check check (estado in ('Borrador', 'Cancelada')),
  constraint venta_borrador_percepciones_check
    check (percepcion_iva >= 0 and percepcion_iibb >= 0),
  constraint venta_borrador_importe_check
    check (importe_pagado is null or importe_pagado >= 0)
);

create table if not exists public.detalle_venta_borrador (
  id_detalle_borrador bigint generated by default as identity primary key,
  id_borrador bigint not null references public.venta_borrador(id_borrador) on delete cascade,
  id_articulo integer not null references public.articulo(id_articulo),
  id_articulo_deposito integer not null references public.articulo_deposito(id_articulo_deposito),
  cantidad integer not null,
  precio_unitario numeric(14, 2) not null,
  alicuota_iva numeric(4, 1) not null,
  constraint detalle_venta_borrador_cantidad_check check (cantidad > 0),
  constraint detalle_venta_borrador_precio_check check (precio_unitario > 0),
  constraint detalle_venta_borrador_iva_check check (alicuota_iva in (0, 10.5, 21)),
  constraint detalle_venta_borrador_articulo_unique unique (id_borrador, id_articulo_deposito)
);

create index if not exists venta_borrador_estado_fecha_idx
  on public.venta_borrador (estado, fecha_actualizacion desc);

grant select on table public.venta_borrador to anon, authenticated;
grant select on table public.detalle_venta_borrador to anon, authenticated;

create or replace function public.guardar_venta_borrador(
  p_id_borrador bigint,
  p_id_sucursal integer,
  p_id_deposito integer,
  p_id_cliente integer,
  p_id_lista integer,
  p_items jsonb,
  p_id_medio_pago integer default null,
  p_importe_pagado numeric default null,
  p_referencia_pago text default null,
  p_percepcion_iva numeric default 0,
  p_percepcion_iibb numeric default 0,
  p_idempotency_key uuid default null
)
returns public.venta_borrador
language plpgsql
security definer
set search_path = public
as $$
declare
  v_borrador public.venta_borrador%rowtype;
  v_item jsonb;
begin
  if not exists (
    select 1 from public.deposito
    where id_deposito = p_id_deposito and id_sucursal = p_id_sucursal and estado is true
  ) then
    raise exception 'El depósito no pertenece a la sucursal o se encuentra inactivo';
  end if;

  if coalesce(p_percepcion_iva, 0) < 0 or coalesce(p_percepcion_iibb, 0) < 0 then
    raise exception 'Las percepciones no pueden ser negativas';
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array' then
    raise exception 'Los ítems del borrador deben enviarse como un arreglo';
  end if;

  if p_id_borrador is null then
    insert into public.venta_borrador (
      id_sucursal, id_deposito, id_cliente, id_lista,
      id_medio_pago, importe_pagado, referencia_pago,
      percepcion_iva, percepcion_iibb, idempotency_key
    ) values (
      p_id_sucursal, p_id_deposito, p_id_cliente, p_id_lista,
      p_id_medio_pago, p_importe_pagado, nullif(trim(coalesce(p_referencia_pago, '')), ''),
      coalesce(p_percepcion_iva, 0), coalesce(p_percepcion_iibb, 0),
      coalesce(p_idempotency_key, gen_random_uuid())
    ) returning * into v_borrador;
  else
    update public.venta_borrador
    set id_sucursal = p_id_sucursal,
        id_deposito = p_id_deposito,
        id_cliente = p_id_cliente,
        id_lista = p_id_lista,
        id_medio_pago = p_id_medio_pago,
        importe_pagado = p_importe_pagado,
        referencia_pago = nullif(trim(coalesce(p_referencia_pago, '')), ''),
        percepcion_iva = coalesce(p_percepcion_iva, 0),
        percepcion_iibb = coalesce(p_percepcion_iibb, 0),
        fecha_actualizacion = now()
    where id_borrador = p_id_borrador and estado = 'Borrador'
    returning * into v_borrador;

    if not found then
      raise exception 'El borrador no existe o ya fue cancelado';
    end if;

    delete from public.detalle_venta_borrador where id_borrador = p_id_borrador;
  end if;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    insert into public.detalle_venta_borrador (
      id_borrador, id_articulo, id_articulo_deposito, cantidad, precio_unitario, alicuota_iva
    ) values (
      v_borrador.id_borrador,
      (v_item->>'id_articulo')::integer,
      (v_item->>'id_articulo_deposito')::integer,
      (v_item->>'cantidad')::integer,
      (v_item->>'precio_unitario')::numeric,
      (v_item->>'alicuota_iva')::numeric
    );
  end loop;

  return v_borrador;
end;
$$;

create or replace function public.cancelar_venta_borrador(p_id_borrador bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.venta_borrador
  set estado = 'Cancelada', fecha_actualizacion = now()
  where id_borrador = p_id_borrador and estado = 'Borrador';

  if not found then
    raise exception 'El borrador no existe o ya fue cancelado';
  end if;
end;
$$;

-- Envoltorio de HU35 sobre la confirmación atómica de HU39. Si falla la
-- confirmación, tampoco se elimina el borrador ni se asocia parcialmente.
create or replace function public.confirmar_venta_desde_borrador(
  p_id_borrador bigint,
  p_idempotency_key uuid,
  p_id_sucursal integer,
  p_id_deposito integer,
  p_id_cliente integer,
  p_tipo_comprobante text,
  p_id_lista integer,
  p_items jsonb,
  p_id_medio_pago integer,
  p_importe_pagado numeric,
  p_referencia_pago text default null,
  p_percepcion_iva numeric default 0,
  p_percepcion_iibb numeric default 0
)
returns setof public.venta
language plpgsql
security definer
set search_path = public
as $$
declare
  v_venta public.venta%rowtype;
begin
  -- Permite reintentar con seguridad si el cliente perdió la respuesta de una
  -- confirmación que sí alcanzó a completarse.
  select * into v_venta
  from public.venta
  where idempotency_key = p_idempotency_key;

  if found then
    return next v_venta;
    return;
  end if;

  if not exists (
    select 1 from public.venta_borrador
    where id_borrador = p_id_borrador
      and estado = 'Borrador'
  ) then
    raise exception 'El borrador no existe o fue cancelado';
  end if;

  select * into v_venta
  from public.confirmar_venta_transaccional(
    p_idempotency_key, p_id_sucursal, p_id_deposito, p_id_cliente,
    p_tipo_comprobante, p_id_lista, p_items, p_id_medio_pago,
    p_importe_pagado, p_referencia_pago, p_percepcion_iva, p_percepcion_iibb
  );

  delete from public.venta_borrador where id_borrador = p_id_borrador;

  return next v_venta;
end;
$$;

revoke all on function public.guardar_venta_borrador(bigint, integer, integer, integer, integer, jsonb, integer, numeric, text, numeric, numeric, uuid) from public;
revoke all on function public.cancelar_venta_borrador(bigint) from public;
revoke all on function public.confirmar_venta_desde_borrador(bigint, uuid, integer, integer, integer, text, integer, jsonb, integer, numeric, text, numeric, numeric) from public;

grant execute on function public.guardar_venta_borrador(bigint, integer, integer, integer, integer, jsonb, integer, numeric, text, numeric, numeric, uuid) to anon, authenticated;
grant execute on function public.cancelar_venta_borrador(bigint) to anon, authenticated;
grant execute on function public.confirmar_venta_desde_borrador(bigint, uuid, integer, integer, integer, text, integer, jsonb, integer, numeric, text, numeric, numeric) to anon, authenticated;

comment on table public.venta_borrador is
  'Ventas iniciadas o suspendidas que todavía no afectan stock ni numeración fiscal.';
commit;
