-- HU30/HU27: ampliar facturas y relacionar sus renglones con la orden de compra.
-- Esta migracion se ejecuta sobre la tabla factura_proveedor existente.

alter table public.factura_proveedor
  add column if not exists punto_venta integer not null default 1,
  add column if not exists subtotal numeric(14, 2) not null default 0,
  add column if not exists iva numeric(14, 2) not null default 0,
  add column if not exists conceptos_exentos numeric(14, 2) not null default 0,
  add column if not exists conceptos_no_gravados numeric(14, 2) not null default 0,
  add column if not exists fecha_registro timestamptz not null default now();

-- Las facturas existentes no tenian desglose fiscal: se conserva su total como subtotal.
update public.factura_proveedor
set subtotal = importe_total
where subtotal = 0
  and importe_total > 0
  and coalesce(iva, 0) = 0
  and coalesce(conceptos_exentos, 0) = 0
  and coalesce(conceptos_no_gravados, 0) = 0;

alter table public.factura_proveedor
  add constraint factura_proveedor_punto_venta_check
    check (punto_venta between 1 and 99999),
  add constraint factura_proveedor_subtotal_check
    check (subtotal >= 0),
  add constraint factura_proveedor_iva_check
    check (iva >= 0),
  add constraint factura_proveedor_exentos_check
    check (conceptos_exentos >= 0),
  add constraint factura_proveedor_no_gravados_check
    check (conceptos_no_gravados >= 0),
  add constraint factura_proveedor_importes_consistentes_check
    check (abs(importe_total - (subtotal + iva + conceptos_exentos + conceptos_no_gravados)) <= 0.01);

create unique index if not exists factura_proveedor_comprobante_unique_idx
  on public.factura_proveedor (id_proveedor, tipo_comprobante, punto_venta, numero_comprobante);

create index if not exists factura_proveedor_id_orden_compra_idx
  on public.factura_proveedor (id_orden_compra);

create table if not exists public.detalle_factura_proveedor (
  id_detalle_factura bigint generated by default as identity primary key,
  id_factura_proveedor integer not null
    references public.factura_proveedor(id_factura_proveedor) on delete cascade,
  id_detalle_orden_compra integer null
    references public.detalle_orden_compra(id_detalle_orden) on delete restrict,
  id_articulo integer not null
    references public.articulo(id_articulo) on delete restrict,
  cantidad numeric(14, 3) not null check (cantidad > 0),
  precio_unitario numeric(14, 2) not null check (precio_unitario >= 0),
  importe numeric(14, 2) generated always as (round(cantidad * precio_unitario, 2)) stored,
  unique (id_factura_proveedor, id_detalle_orden_compra)
);

create index if not exists detalle_factura_proveedor_id_factura_idx
  on public.detalle_factura_proveedor(id_factura_proveedor);

create index if not exists detalle_factura_proveedor_id_detalle_orden_idx
  on public.detalle_factura_proveedor(id_detalle_orden_compra);

-- Evita asociar una factura con una orden de otro proveedor.
create or replace function public.validar_factura_proveedor_orden()
returns trigger
language plpgsql
as $$
begin
  if new.id_orden_compra is not null and not exists (
    select 1
    from public.orden_compra oc
    where oc.id_orden_compra = new.id_orden_compra
      and oc.id_proveedor = new.id_proveedor
  ) then
    raise exception 'La orden de compra no pertenece al proveedor de la factura';
  end if;
  return new;
end;
$$;

drop trigger if exists factura_proveedor_orden_consistente on public.factura_proveedor;
create trigger factura_proveedor_orden_consistente
before insert or update of id_proveedor, id_orden_compra
on public.factura_proveedor
for each row execute function public.validar_factura_proveedor_orden();

-- Cada renglon debe pertenecer a la orden seleccionada en la cabecera y conservar su articulo.
create or replace function public.validar_detalle_factura_proveedor()
returns trigger
language plpgsql
as $$
declare
  factura_orden bigint;
  detalle_orden bigint;
  detalle_articulo integer;
begin
  select id_orden_compra into factura_orden
  from public.factura_proveedor
  where id_factura_proveedor = new.id_factura_proveedor;

  if new.id_detalle_orden_compra is not null then
    select id_orden_compra, id_articulo
      into detalle_orden, detalle_articulo
    from public.detalle_orden_compra
    where id_detalle_orden = new.id_detalle_orden_compra;

    if factura_orden is null or detalle_orden <> factura_orden then
      raise exception 'El detalle de la orden no coincide con la orden de la factura';
    end if;
    if detalle_articulo <> new.id_articulo then
      raise exception 'El articulo del detalle de factura no coincide con la orden';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists detalle_factura_orden_consistente on public.detalle_factura_proveedor;
create trigger detalle_factura_orden_consistente
before insert or update of id_factura_proveedor, id_detalle_orden_compra, id_articulo
on public.detalle_factura_proveedor
for each row execute function public.validar_detalle_factura_proveedor();
